export type SqlValue = string | number | boolean | null

export interface SqlExecuteResult {
  rowsAffected: number
  lastInsertId?: number
}

export type DatabaseMutation =
  | 'upsertAsset'
  | 'deleteAsset'
  | 'hardDeleteDocument'
  | 'createAgentTask'
  | 'markInterruptedAgentTasks'
  | 'updateAgentTask'
  | 'upsertAgentToolCall'
  | 'saveAgentWorkspaceState'
  | 'createAutomationTask'
  | 'setAutomationTaskEnabled'
  | 'deleteAutomationTask'
  | 'enqueueAutomationRun'
  | 'updateAutomationRun'
  | 'createWorkspaceView'
  | 'updateWorkspaceView'
  | 'moveWorkspaceView'
  | 'setWorkspaceViewPinned'
  | 'deleteWorkspaceView'
  | 'createMindMap'
  | 'moveMindMap'
  | 'updateMindMap'
  | 'deleteMindMap'
  | 'createInformationHome'
  | 'updateInformationHomePayload'
  | 'updateInformationHomeSettings'
  | 'createInformationHomeSummary'
  | 'createEmailAccount'
  | 'deleteEmailAccount'
  | 'updateEmailSyncState'
  | 'updateEmailCategory'
  | 'upsertEmailMessage'
  | 'setEmailMessageStatus'
  | 'deleteEmailMessage'
  | 'blockEmailSender'
  | 'unblockEmailSender'
  | 'createImConnector'
  | 'deleteImConnector'
  | 'updateImCategory'
  | 'setImConnectorEnabled'
  | 'setImMessageStatus'
  | 'createRssSource'
  | 'deleteRssSource'
  | 'updateRssSyncState'
  | 'updateRssCategory'
  | 'upsertRssEntry'
  | 'setRssEntryStatus'
  | 'updateRssArticleContent'
  | 'createKnowledgeObject'
  | 'updateKnowledgeObject'
  | 'deleteKnowledgeRelations'
  | 'deleteKnowledgeSources'
  | 'deleteKnowledgeValidations'
  | 'deleteKnowledgeObject'
  | 'addKnowledgeRelation'
  | 'addKnowledgeSource'
  | 'addKnowledgeValidation'
  | 'createViewDefinition'
  | 'createTaskDefinition'
  | 'createTaskRun'
  | 'updateTaskRun'
  | 'addWorkArtifact'
  | 'addWorkEvidence'
  | 'createChangeSet'

export interface SqlClient {
  mutate(mutation: DatabaseMutation, bindValues?: SqlValue[]): Promise<SqlExecuteResult>
  select<T extends Record<string, unknown>>(sql: string, bindValues?: SqlValue[]): Promise<T[]>
  close?(): Promise<boolean>
}
